### ISSUE TITLE
 double press issue

### ISSUE THREAD

**Issue by Alex-Github-Account** [8LWXpg/RegExHotstring#2]
my script is from demo:

```
#Requires AutoHotkey v2.0
#Include RegExHotstring.ahk
#SingleInstance Force

; the upmost function will be triggered first

; replace with regex string

RegExHotstring("(\w*)c", call)
; receives RegExMatchInfo
call(match) {
	MsgBox("matched: " match[1])
}
```

when  I press a button, it does not do anything untill I press it again. Then it produces one symbol as expected.
e.g. to enter word 
`example`
I need to press
`eexxaammppllee`
same time hotstring functionality works, e.g.  if I enter
`eexxaammpplleecc`
then it would trigger call function (assuming hitting space at the end)

I am using fresh (just downladed) ahk v2 install, also have v1.1 instaled alongside (ahk claims they compatible to be installed together) and no other scripts running. As soon as I close this test script, doublepress issue gone.

What can I do to debug? where to watch?

**Comment by 8LWXpg** [comment]
> What can I do to debug? where to watch?

I use vscode for debugging and editing. Also, there's a ToolTip inside `RegExHs.char()` that can peek the input it receives, or double tap the tray icon then view key history.

I didn't find the bug you mentioned but find one with keyup not sending properly, does it fix your problem?

**Comment by Alex-Github-Account** [comment]
Ok I got it: it is issue with autohotkey 2.0 itself, it requires doublepress outside yours script too, so this is not your script issue.
