### ISSUE TITLE
! # ^ { } and + will not trigger match with \W

### ISSUE THREAD

**Issue by EFH52** [8LWXpg/RegExHotstring#5]
I use:
`RegExHotstring("psa(s)?(\W)", "Please see the attached document$1$2", "*C")`

! # ^ { } and + will not trigger match when they are the terminal characters. Practically speaking , the only one likely to cause me issue in the day to day is the !.

**Comment by 8LWXpg** [comment]
use SendText with new option `T`

`RegExHotstring("psa(s)?(\W)", "Please see the attached document$1$2", "*CT")`
