### ISSUE TITLE
Regular hotstrings stop working when #Include-ing RegExHotString.ahk

### ISSUE THREAD

**Issue by wwwald** [8LWXpg/RegExHotstring#8]
I'm trying to extend my existing Hotkey script with regex hotstrings, based on your script.
Whenever I try to `#Include` the `RegExHotString.ahk` file, though, my "regular" hotstring definitions stop working.

Example script 1, without `#Include RegExHotString.ahk`:
```ahk
#SingleInstance Force
TrayTip("AHK script '" . A_ScriptName . "' loading ...", , 1)

:X:;dt::SendInput(FormatTime(, "yyyy-MM-dd HH'h'mm"))

#Home::SoundSetMute(!SoundGetMute())
```
→ the `;dt` hotstring works, the `#Home` hotkey works.

Example script 2, with `#Include RegExHotString.ahk` and an example regex hotstring to generate a Markdown link:
```ahk
#SingleInstance Force
TrayTip("AHK script '" . A_ScriptName . "' loading ...", , 1)

:X:;dt::SendInput(FormatTime(, "yyyy-MM-dd HH'h'mm"))

#Home::SoundSetMute(!SoundGetMute())

#Include %A_ScriptDir%\_inc\RegExHotstring.ahk
RegExHotstring(";issue([0-9]+)", "[ISSUE-$1](http://jira.mydomein.com/browse/PROJ-$1)", "O")
```
→ the `#Home` hotkey still works, the  `;issue` regex hotstring works... but the regular `;dt` hotstring does NOT work anymore.

I'm guessing this has to do with some interference between the `InputHook` in RegExHotString versus my regular hotstrings... but I don't know anything about how those work.

Can you see what's causing the problem? How to make this work?

**Comment by 8LWXpg** [comment]
I can't replicate the issue with following script:
```ahk
#SingleInstance Force
:X:;dt:: SendInput(FormatTime(, "yyyy-MM-dd HH'h'mm"))

#Include RegExHotstring.ahk
RegExHotstring(";issue([0-9]+)", "[ISSUE-$1](http://jira.mydomein.com/browse/PROJ-$1)", "O")
```

Did you modified the `#InputLevel` before Hotstring or using the older version of the script?

**Comment by 8LWXpg** [comment]
I removed `SendLevel` in script, now it's up to users to decide where to change `SendLevel`.

Doc is added [here](https://github.com/8LWXpg/RegExHotstring?tab=readme-ov-file#how-to-trigger-regular-hotstring-in-the-same-script)

Please reopen if you still experience similar issues.

**Comment by wwwald** [comment]
I still can't get it to work in a simple example:
```
#Include %A_ScriptDir%\_inc\RegExHotstring.ahk

:X:;dt:: SendInput(FormatTime(, "yyyy-MM-dd HH'h'mm"))

RegHook.MinSendLevel := 2
SendLevel(1)

RegExHotstring(";issue([0-9]+)", "[ISSUE-$1](http://jira.mydomein.com/browse/PROJ-$1)", "O")
```
In this case, the  `;issue` regex hotstring works but the `;dt` does not... but the code sample is almost exactly what you show in the FAQ documentation.

I'm confused by the whole `SendLevel` / `InputLevel` mechanism in Autohotkey, so I'm still trying to get this working by trial & error :-(

**Comment by 8LWXpg** [comment]
That's unfortunate
![2024-04-23 205724](https://github.com/8LWXpg/RegExHotstring/assets/105704427/1f1b8bab-e2a0-47ee-9409-209125d9fc8e)

If you’re still having trouble getting it to work, consider creating `RegExHotString`s in a separate file. This approach should work without changing the settings.

There's a lot of hidden logic behind `SendLevel`/`InputLevel`, and the documentation is not clear enough. If you find yourself needing further assistance, don’t hesitate to post your questions on the [official form](https://www.autohotkey.com/boards)
